--- #YAML:1.0
name:               Logger-Fq
version:            0.2.12
abstract:           Log to Fq (asynchronously)
author:
    - Theo Schlossnagle <jesus@lethargy.org>
license:            MIT
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Variable::Magic:      0
requires:
    ExtUtils::MakeMaker:  6.03
    Test::More:           0
    Scalar::Util:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
